### ISSUE TITLE
Module Shows “Connected” but will not control unit.

### ISSUE THREAD

**Issue by howlingwolf487** [bitfocus/companion-module-roland-v160hd#1]
Thanks for the help! Info below.

Using the latest Companion beta release for Windows (2.3.0+4521-beta-01355dff

Unit is on v1.11 firmware.

Roland’s control software was not open at the same time.

I am using the LAN connection and can successfully ping the switcher from my laptop.

When enabled in Companion, the module status shows CONNECTED. The Control PIN matches the switcher’s settings.

I made some buttons and wanted to pick an Input to go to the PVW bus, but when I click the button in the emulator, it doesn’t work.

I have a Roland V-60HD in this show as well. The controls I programmed on the same button as the V-160HD were working properly for the V-60HD.

**Comment by josephdadams** [comment]
If I pushed a version that gave more verbose responses to the log in Companion, would you be able to share that with me?

**Comment by howlingwolf487** [comment]
I can probably do that. Would I just update the whole Companion program, then?

I’ll be onsite the next two days, so I can try to sneak in and work on that.

**Comment by josephdadams** [comment]
Yes it would just be a whole new version. I will see if I can get that done soon

**Comment by howlingwolf487** [comment]
Coolness.

Oh, and ai remembered one thing: how do you initiate a CUT or AUTO transition using the module? I couldn’t find that in the list of available actions…did I just miss it/is it burier somewhere I’m not aware of?

Thanks again!

**Comment by josephdadams** [comment]
I pushed a new version, be sure to edit the module config and enable verbose logging.

**Comment by howlingwolf487** [comment]
Awesome! I’ll download it now and can install it and adjust those settings around lunchtime.

**Comment by josephdadams** [comment]
Please try the module again :)

**Comment by howlingwolf487** [comment]
Hi Joseph,

I am unable to do so at this time - the v160 switcher was a sub-rental, so I don’t have it available to test with.

If/when we bring one in again, I will be sure to do so.

Thanks for the follow-up!

- Jordan
