### ISSUE TITLE
No way to change camera selection

### ISSUE THREAD

**Issue by Longstreth-65** [bitfocus/companion-module-roland-v160hd#12]
When recalling PTZ presets (or otherwise controlling PTZs, there is no option for a button to change which camera is being affected (camera selection)

**Comment by josephdadams** [comment]
<img width="713" alt="Screenshot 2024-06-18 at 1 19 24 PM" src="https://github.com/bitfocus/companion-module-roland-v160hd/assets/2559091/3934d7a2-9492-47df-af6f-38096c7a144f">

I disagree

**Comment by Longstreth-65** [comment]
My application is I'm using a game controller for PTZ, which I can do, but I want to use a stream deck mini to choose which camera applies to the controller (is selected)

**Comment by Longstreth-65** [comment]
I'm in process with Roland to see where that is located in their API as it is not in the manual they provide, and if I may be able to do it from, a TCP command instead. As of now, the only way it's possible is by physically going into the UI of RCS software and clicking to select a camera

**Comment by josephdadams** [comment]
All of the commands include specifying the camera in the command. One option would be to modify the command from companion to allow custom variables, and then just use the stream deck mini to change the variable value.

**Comment by Longstreth-65** [comment]
Awesome. I'll try it that way. Thanks!

**Comment by josephdadams** [comment]
The module will have to be modified to support that.

**Comment by josephdadams** [comment]
I added a new action to allow you to select a camera, and then an option to every camera action to use the selected camera instead of the one from the dropdown list. Maybe this will help you on your journey. It is `v2.1.0` of the module.
