### ISSUE TITLE
Automatically Reconnect?

### ISSUE THREAD

**Issue by mikethiessen21** [bitfocus/companion-module-roland-v160hd#2]
I am finding that I need to manually reconnect this module to my V-160HD every time I use it. Is there a way to have the module automatically connect?

**Comment by josephdadams** [comment]
You mean like disable and enable the module?

**Comment by mikethiessen21** [comment]
Yes, that is what I mean. I usually wake the computer from sleep and then turn on the video switcher. The switcher is new for me and I just started using this module. So far I always need to disable and then re-enable the module before it works.

**Comment by josephdadams** [comment]
Ah, I see. So the module is trying to connect but can't, so it throws an error. This is the same behavior you'd see if it was the wrong IP.

The only real way to fix this would be to modify the code to run an interval every x seconds that retries.

Could you accomplish this with a trigger? If the module is in an error state, disable and enable it?

**Comment by mikethiessen21** [comment]
Thanks for the idea. I was able to make it work with a trigger except that I could not find feedback for specific modules.If I use the variable instance_errors I can check if there is at least one module with an error, but other modules could also cause the action to run.If this module could provide feedback for connection status then a trigger would work for this. It would be nice to just have this built-in, though.
-------- Original message --------From: Joseph Adams ***@***.***> Date: 2023-03-03  5:41 a.m.  (GMT-08:00) To: bitfocus/companion-module-roland-v160hd ***@***.***> Cc: Mike ***@***.***>, Author ***@***.***> Subject: Re: [bitfocus/companion-module-roland-v160hd] Automatically Reconnect? (Issue #2) 
Ah, I see. So the module is trying to connect but can't, so it throws an error. This is the same behavior you'd see if it was the wrong IP.
The only real way to fix this would be to modify the code to run an interval every x seconds that retries.
Could you accomplish this with a trigger? If the module is in an error state, disable and enable it?

**Comment by josephdadams** [comment]
This feature is available now in the latest `v2.0.0` of the module.
