### ISSUE TITLE
AUX 2 and AUX 3 Support

### ISSUE THREAD

**Issue by roopeberg** [bitfocus/companion-module-roland-v160hd#6]
Roland added two new aux buses on SW Ver 3.0. It would be really great to be able to asign also these two new aux2 and aux3 busses with this module. 

Link to Roland: 
https://proav.roland.com/global/support/by_product/v-160hd/updates_drivers/8534fcec-b377-418f-b103-41cd2d4f4d7e/

**Comment by gethindavies** [comment]
Second this! Happy to put some sponsorship towards the development of this update. Many thanks in advance

**Comment by EFetcho** [comment]
Same, How do we sponsor this?

**Comment by roopeberg** [comment]
I would also like to sponsor this.

**Comment by josephdadams** [comment]
Can you guys email me? My email is on my github profile. Then I can start a new thread with all 3 of us.

**Comment by josephdadams** [comment]
This feature is available now in the latest `v2.0.0` of the module. :)
