### ISSUE TITLE
Select Source action appears broken after firmware update

### ISSUE THREAD

**Issue by Skidizzle** [bitfocus/companion-module-roland-v160hd#9]
Using Companion (3.1.2+6243-stable-05c37a10)
[SBOT Streamdeck.zip](https://github.com/bitfocus/companion-module-roland-v160hd/files/14853932/SBOT.Streamdeck.zip)

Relevant settings on the Roland itself are
PVW input 10 is set to Still 1
PGM input 10 is set to Still 1

I have 2 buttons that are supposed to each bring up 2 pips and the background still that's assigned to input 10.

After updating the 160 firmware to 3.01 these buttons are no longer selecting the correct input on either the PVW or PGM bus.

**Comment by Skidizzle** [comment]
[config files.zip](https://github.com/bitfocus/companion-module-roland-v160hd/files/14875731/config.files.zip)

Adding the Roland config files in case that helps

**Comment by josephdadams** [comment]
This should be fixed in the latest `v2.0.0` of the module. :)
